version: "3"
services:

  golang1.19:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: golang1.19
    restart: unless-stopped
    working_dir: /app
    ports:
      - 8088:8088
      - 443:443
    volumes:
      - .:/app
