server : 
  port: :8087
database: 
  host: localhost
  username: root
  password: 1234
  dbname: company
  port: 3306
common:
  ENV: local | prod (choose one)
  PROJECT_ROOT: AUTO_GET
  UPLOADS_PATH: static/uploads
  LINE_MESSAGING_API_ACCESS_TOKEN: {LINE_ASSESS_TOKEN}
